name: Links
favicon: null
layout_spectrum: 0
typography_spectrum: 0.26064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#7e7e7e'
    - '#cecece'
    - '#505050'
    - '#a9a9a9'
  brandStrength: 1
  lightness: 0.9406125547830015
  saturation: 0.8011180644389242
  rhythmicContrast: 0.75
purpose: []
